project_id = "rkgjsusoycmyehvurupy"

[functions.send-telegram-notification]
verify_jwt = false

[functions.api-football]
verify_jwt = false

[functions.fetch-live-stats]
verify_jwt = false

[functions.search-live-fixtures]
verify_jwt = false

[functions.sync-google-sheets]
verify_jwt = false

[functions.manage-vapid-keys]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-fixture-details]
verify_jwt = false

[functions.the-odds-api]
verify_jwt = false

[functions.analyze-performance]
verify_jwt = false

[functions.check-goals-and-notify]
verify_jwt = false

[functions.elevenlabs-sfx]
verify_jwt = false

[functions.analyze-method]
verify_jwt = false
