project_id = "rkgjsusoycmyehvurupy"

[functions.monitor-live-games]
verify_jwt = false

[functions.check-goals-and-notify]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.analyze-live-moment]
verify_jwt = false
